### ISSUE TITLE
Rod conversion is inverted

### ISSUE THREAD

**Issue by drobert** [JavadocMD/simplelatlng#12]
I can honestly say I never thought I'd open a ticket concerning conversion of Rods to another unit of distance...

In com.javadocmd.simplelatlng.util.LengthUnit, ROD is defined as "0.0050292 rods to the kilometer", however that scalar represents the number of kilometers per rod.

The correct value should be 198.839 rods per kilometer.

**Comment by JavadocMD** [comment]
Good heavens!

**Comment by JavadocMD** [comment]
Fixed for release v1.3.1.
